[[headers]]

for = "/*"

[headers.values]

Content-Security-Policy = "frame-ancestors catch-of-the-day-2.netlify.com"
Referrer-Policy = "strict-origin"
Strict-Transport-Security = "max-age=31536000"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
proxy_hide_header = "X-Powered-By"


[build.environment]

NODE_VERSION = "9"
YARN_VERSION = "0.28.4"

[[redirects]]
from = "http://catch-of-the-day-2.netlify.com"
to = "https://catch-of-the-day-2.netlify.com:443"
status = 301
force = true